<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Tests;

use Core\Types\CallbackCatcher;
use ShellEVLib\Authentication\ClientCredentialsAuthCredentialsBuilder;
use ShellEVLib\ShellEVClient;
use ShellEVLib\ShellEVClientBuilder;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): ShellEVClient
    {
        $clientBuilder = ShellEVClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        $client = $clientBuilder->httpCallback($httpCallback)->build();
        $oAuthToken = $client->getClientCredentialsAuth()->fetchToken();
        $clientBuilder->clientCredentialsAuthCredentials(
            $client->getClientCredentialsAuthCredentialsBuilder()->oAuthToken($oAuthToken)
        );
        return $clientBuilder->build();
    }

    public static function addTestConfiguration(ShellEVClientBuilder $builder): ShellEVClientBuilder
    {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(ShellEVClientBuilder $builder): ShellEVClientBuilder
    {
        $timeout = getenv('SHELL_EV_LIB_TIMEOUT');
        $numberOfRetries = getenv('SHELL_EV_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('SHELL_EV_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('SHELL_EV_LIB_ENVIRONMENT');
        $env = getenv('SHELL_EV_LIB_ENV');
        $oAuthClientId = getenv('SHELL_EV_LIB_O_AUTH_CLIENT_ID');
        $oAuthClientSecret = getenv('SHELL_EV_LIB_O_AUTH_CLIENT_SECRET');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        if (!empty($env)) {
            $builder->env($env);
        }

        if (!empty($oAuthClientId) && !empty($oAuthClientSecret)) {
            $builder->clientCredentialsAuthCredentials(
                ClientCredentialsAuthCredentialsBuilder::init($oAuthClientId, $oAuthClientSecret)
            );
        }

        return $builder;
    }
}
