<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\Accessibility;

/**
 * Builder for model Accessibility
 *
 * @see Accessibility
 */
class AccessibilityBuilder
{
    /**
     * @var Accessibility
     */
    private $instance;

    private function __construct(Accessibility $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Accessibility Builder object.
     */
    public static function init(): self
    {
        return new self(new Accessibility());
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets remark field.
     *
     * @param string|null $value
     */
    public function remark(?string $value): self
    {
        $this->instance->setRemark($value);
        return $this;
    }

    /**
     * Initializes a new Accessibility object.
     */
    public function build(): Accessibility
    {
        return CoreHelper::clone($this->instance);
    }
}
