<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\ActiveResponse200Json;
use ShellEVLib\Models\DataActive;

/**
 * Builder for model ActiveResponse200Json
 *
 * @see ActiveResponse200Json
 */
class ActiveResponse200JsonBuilder
{
    /**
     * @var ActiveResponse200Json
     */
    private $instance;

    private function __construct(ActiveResponse200Json $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Active Response 200 Json Builder object.
     *
     * @param string $requestId
     * @param string $status
     */
    public static function init(string $requestId, string $status): self
    {
        return new self(new ActiveResponse200Json($requestId, $status));
    }

    /**
     * Sets data field.
     *
     * @param DataActive[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new Active Response 200 Json object.
     */
    public function build(): ActiveResponse200Json
    {
        return CoreHelper::clone($this->instance);
    }
}
