<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\BadRequestErrMsg;

/**
 * Builder for model BadRequestErrMsg
 *
 * @see BadRequestErrMsg
 */
class BadRequestErrMsgBuilder
{
    /**
     * @var BadRequestErrMsg
     */
    private $instance;

    private function __construct(BadRequestErrMsg $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new bad request err msg Builder object.
     */
    public static function init(): self
    {
        return new self(new BadRequestErrMsg());
    }

    /**
     * Sets code field.
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets details field.
     */
    public function details(?array $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Initializes a new bad request err msg object.
     */
    public function build(): BadRequestErrMsg
    {
        return CoreHelper::clone($this->instance);
    }
}
