<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\ChargesessionStartBody;

/**
 * Builder for model ChargesessionStartBody
 *
 * @see ChargesessionStartBody
 */
class ChargesessionStartBodyBuilder
{
    /**
     * @var ChargesessionStartBody
     */
    private $instance;

    private function __construct(ChargesessionStartBody $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new chargesession start body Builder object.
     */
    public static function init(string $evChargeNumber, string $evseId): self
    {
        return new self(new ChargesessionStartBody($evChargeNumber, $evseId));
    }

    /**
     * Initializes a new chargesession start body object.
     */
    public function build(): ChargesessionStartBody
    {
        return CoreHelper::clone($this->instance);
    }
}
