<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\ChargeError;
use ShellEVLib\Models\ChargeRetrieveState;

/**
 * Builder for model ChargeRetrieveState
 *
 * @see ChargeRetrieveState
 */
class ChargeRetrieveStateBuilder
{
    /**
     * @var ChargeRetrieveState
     */
    private $instance;

    private function __construct(ChargeRetrieveState $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new charge retrieve state Builder object.
     */
    public static function init(): self
    {
        return new self(new ChargeRetrieveState());
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets error field.
     */
    public function error(?ChargeError $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Initializes a new charge retrieve state object.
     */
    public function build(): ChargeRetrieveState
    {
        return CoreHelper::clone($this->instance);
    }
}
