<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\ChargeError;

/**
 * Builder for model ChargeError
 *
 * @see ChargeError
 */
class ChargeErrorBuilder
{
    /**
     * @var ChargeError
     */
    private $instance;

    private function __construct(ChargeError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new charge error Builder object.
     */
    public static function init(): self
    {
        return new self(new ChargeError());
    }

    /**
     * Sets code field.
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Initializes a new charge error object.
     */
    public function build(): ChargeError
    {
        return CoreHelper::clone($this->instance);
    }
}
