<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\ConnectorVO;
use ShellEVLib\Models\ElectricalProperties;
use ShellEVLib\Models\Tariff;

/**
 * Builder for model ConnectorVO
 *
 * @see ConnectorVO
 */
class ConnectorVOBuilder
{
    /**
     * @var ConnectorVO
     */
    private $instance;

    private function __construct(ConnectorVO $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Connector VO Builder object.
     */
    public static function init(): self
    {
        return new self(new ConnectorVO());
    }

    /**
     * Sets uid field.
     *
     * @param int|null $value
     */
    public function uid(?int $value): self
    {
        $this->instance->setUid($value);
        return $this;
    }

    /**
     * Sets external Id field.
     *
     * @param string|null $value
     */
    public function externalId(?string $value): self
    {
        $this->instance->setExternalId($value);
        return $this;
    }

    /**
     * Sets connector Type field.
     *
     * @param string|null $value
     */
    public function connectorType(?string $value): self
    {
        $this->instance->setConnectorType($value);
        return $this;
    }

    /**
     * Sets electrical Properties field.
     *
     * @param ElectricalProperties|null $value
     */
    public function electricalProperties(?ElectricalProperties $value): self
    {
        $this->instance->setElectricalProperties($value);
        return $this;
    }

    /**
     * Sets fixed Cable field.
     *
     * @param bool|null $value
     */
    public function fixedCable(?bool $value): self
    {
        $this->instance->setFixedCable($value);
        return $this;
    }

    /**
     * Sets tariff field.
     *
     * @param Tariff|null $value
     */
    public function tariff(?Tariff $value): self
    {
        $this->instance->setTariff($value);
        return $this;
    }

    /**
     * Sets updated field.
     *
     * @param string|null $value
     */
    public function updated(?string $value): self
    {
        $this->instance->setUpdated($value);
        return $this;
    }

    /**
     * Sets updated By field.
     *
     * @param string|null $value
     */
    public function updatedBy(?string $value): self
    {
        $this->instance->setUpdatedBy($value);
        return $this;
    }

    /**
     * Sets deleted field.
     *
     * @param string|null $value
     */
    public function deleted(?string $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Initializes a new Connector VO object.
     */
    public function build(): ConnectorVO
    {
        return CoreHelper::clone($this->instance);
    }
}
