<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\ConnectorVO;
use ShellEVLib\Models\EvseVO;

/**
 * Builder for model EvseVO
 *
 * @see EvseVO
 */
class EvseVOBuilder
{
    /**
     * @var EvseVO
     */
    private $instance;

    private function __construct(EvseVO $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Evse VO Builder object.
     */
    public static function init(): self
    {
        return new self(new EvseVO());
    }

    /**
     * Sets uid field.
     *
     * @param int|null $value
     */
    public function uid(?int $value): self
    {
        $this->instance->setUid($value);
        return $this;
    }

    /**
     * Sets external Id field.
     *
     * @param string|null $value
     */
    public function externalId(?string $value): self
    {
        $this->instance->setExternalId($value);
        return $this;
    }

    /**
     * Sets evse Id field.
     *
     * @param string|null $value
     */
    public function evseId(?string $value): self
    {
        $this->instance->setEvseId($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets connectors field.
     *
     * @param ConnectorVO[]|null $value
     */
    public function connectors(?array $value): self
    {
        $this->instance->setConnectors($value);
        return $this;
    }

    /**
     * Sets authorization Methods field.
     *
     * @param string|null $value
     */
    public function authorizationMethods(?string $value): self
    {
        $this->instance->setAuthorizationMethods($value);
        return $this;
    }

    /**
     * Sets updated field.
     *
     * @param string|null $value
     */
    public function updated(?string $value): self
    {
        $this->instance->setUpdated($value);
        return $this;
    }

    /**
     * Sets deleted field.
     *
     * @param string|null $value
     */
    public function deleted(?string $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Sets physical Reference field.
     *
     * @param string|null $value
     */
    public function physicalReference(?string $value): self
    {
        $this->instance->setPhysicalReference($value);
        return $this;
    }

    /**
     * Initializes a new Evse VO object.
     */
    public function build(): EvseVO
    {
        return CoreHelper::clone($this->instance);
    }
}
