<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\InlineResponse202Data;

/**
 * Builder for model InlineResponse202Data
 *
 * @see InlineResponse202Data
 */
class InlineResponse202DataBuilder
{
    /**
     * @var InlineResponse202Data
     */
    private $instance;

    private function __construct(InlineResponse202Data $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Inline Response 202 Data Builder object.
     */
    public static function init(): self
    {
        return new self(new InlineResponse202Data());
    }

    /**
     * Sets session Id field.
     *
     * @param string|null $value
     */
    public function sessionId(?string $value): self
    {
        $this->instance->setSessionId($value);
        return $this;
    }

    /**
     * Initializes a new Inline Response 202 Data object.
     */
    public function build(): InlineResponse202Data
    {
        return CoreHelper::clone($this->instance);
    }
}
