<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\InlineResponse2021;

/**
 * Builder for model InlineResponse2021
 *
 * @see InlineResponse2021
 */
class InlineResponse2021Builder
{
    /**
     * @var InlineResponse2021
     */
    private $instance;

    private function __construct(InlineResponse2021 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Inline Response 2021 Builder object.
     *
     * @param string $requestId
     * @param string $status
     */
    public static function init(string $requestId, string $status): self
    {
        return new self(new InlineResponse2021($requestId, $status));
    }

    /**
     * Initializes a new Inline Response 2021 object.
     */
    public function build(): InlineResponse2021
    {
        return CoreHelper::clone($this->instance);
    }
}
