<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\InlineResponse202;
use ShellEVLib\Models\InlineResponse202Data;

/**
 * Builder for model InlineResponse202
 *
 * @see InlineResponse202
 */
class InlineResponse202Builder
{
    /**
     * @var InlineResponse202
     */
    private $instance;

    private function __construct(InlineResponse202 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Inline Response 202 Builder object.
     *
     * @param string $requestId
     * @param string $status
     * @param InlineResponse202Data[] $data
     */
    public static function init(string $requestId, string $status, array $data): self
    {
        return new self(new InlineResponse202($requestId, $status, $data));
    }

    /**
     * Initializes a new Inline Response 202 object.
     */
    public function build(): InlineResponse202
    {
        return CoreHelper::clone($this->instance);
    }
}
