<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\InternalErrorObject;

/**
 * Builder for model InternalErrorObject
 *
 * @see InternalErrorObject
 */
class InternalErrorObjectBuilder
{
    /**
     * @var InternalErrorObject
     */
    private $instance;

    private function __construct(InternalErrorObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new internal error object Builder object.
     */
    public static function init(): self
    {
        return new self(new InternalErrorObject());
    }

    /**
     * Sets code field.
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Initializes a new internal error object object.
     */
    public function build(): InternalErrorObject
    {
        return CoreHelper::clone($this->instance);
    }
}
