<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\Accessibility;
use ShellEVLib\Models\Address;
use ShellEVLib\Models\Coordinates;
use ShellEVLib\Models\LocationResponeObject;

/**
 * Builder for model LocationResponeObject
 *
 * @see LocationResponeObject
 */
class LocationResponeObjectBuilder
{
    /**
     * @var LocationResponeObject
     */
    private $instance;

    private function __construct(LocationResponeObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new location respone object Builder object.
     */
    public static function init(): self
    {
        return new self(new LocationResponeObject());
    }

    /**
     * Sets uid field.
     */
    public function uid(?int $value): self
    {
        $this->instance->setUid($value);
        return $this;
    }

    /**
     * Sets external id field.
     */
    public function externalId(?string $value): self
    {
        $this->instance->setExternalId($value);
        return $this;
    }

    /**
     * Sets coordinates field.
     */
    public function coordinates(?Coordinates $value): self
    {
        $this->instance->setCoordinates($value);
        return $this;
    }

    /**
     * Sets operator name field.
     */
    public function operatorName(?string $value): self
    {
        $this->instance->setOperatorName($value);
        return $this;
    }

    /**
     * Sets address field.
     */
    public function address(?Address $value): self
    {
        $this->instance->setAddress($value);
        return $this;
    }

    /**
     * Sets accessibility field.
     */
    public function accessibility(?Accessibility $value): self
    {
        $this->instance->setAccessibility($value);
        return $this;
    }

    /**
     * Sets evses field.
     */
    public function evses(?array $value): self
    {
        $this->instance->setEvses($value);
        return $this;
    }

    /**
     * Sets opening hours field.
     */
    public function openingHours(?array $value): self
    {
        $this->instance->setOpeningHours($value);
        return $this;
    }

    /**
     * Sets updated field.
     */
    public function updated(?string $value): self
    {
        $this->instance->setUpdated($value);
        return $this;
    }

    /**
     * Sets operator comment field.
     */
    public function operatorComment(?string $value): self
    {
        $this->instance->setOperatorComment($value);
        return $this;
    }

    /**
     * Sets location type field.
     */
    public function locationType(?string $value): self
    {
        $this->instance->setLocationType($value);
        return $this;
    }

    /**
     * Initializes a new location respone object object.
     */
    public function build(): LocationResponeObject
    {
        return CoreHelper::clone($this->instance);
    }
}
