<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\M400ErrorResponseError;

/**
 * Builder for model M400ErrorResponseError
 *
 * @see M400ErrorResponseError
 */
class M400ErrorResponseErrorBuilder
{
    /**
     * @var M400ErrorResponseError
     */
    private $instance;

    private function __construct(M400ErrorResponseError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new m400 error response error Builder object.
     */
    public static function init(string $code, string $title, string $detail): self
    {
        return new self(new M400ErrorResponseError($code, $title, $detail));
    }

    /**
     * Sets additional info field.
     */
    public function additionalInfo(?array $value): self
    {
        $this->instance->setAdditionalInfo($value);
        return $this;
    }

    /**
     * Unsets additional info field.
     */
    public function unsetAdditionalInfo(): self
    {
        $this->instance->unsetAdditionalInfo();
        return $this;
    }

    /**
     * Initializes a new m400 error response error object.
     */
    public function build(): M400ErrorResponseError
    {
        return CoreHelper::clone($this->instance);
    }
}
