<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\M404ErrorResponse;

/**
 * Builder for model M404ErrorResponse
 *
 * @see M404ErrorResponse
 */
class M404ErrorResponseBuilder
{
    /**
     * @var M404ErrorResponse
     */
    private $instance;

    private function __construct(M404ErrorResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new m404 error response Builder object.
     */
    public static function init(string $requestId, string $status): self
    {
        return new self(new M404ErrorResponse($requestId, $status));
    }

    /**
     * Sets errors field.
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new m404 error response object.
     */
    public function build(): M404ErrorResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
