<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\M405ErrorResponse;

/**
 * Builder for model M405ErrorResponse
 *
 * @see M405ErrorResponse
 */
class M405ErrorResponseBuilder
{
    /**
     * @var M405ErrorResponse
     */
    private $instance;

    private function __construct(M405ErrorResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new m405 error response Builder object.
     */
    public static function init(string $requestId, string $status): self
    {
        return new self(new M405ErrorResponse($requestId, $status));
    }

    /**
     * Sets errors field.
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new m405 error response object.
     */
    public function build(): M405ErrorResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
