<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\M429ErrorResponse;

/**
 * Builder for model M429ErrorResponse
 *
 * @see M429ErrorResponse
 */
class M429ErrorResponseBuilder
{
    /**
     * @var M429ErrorResponse
     */
    private $instance;

    private function __construct(M429ErrorResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new m429 error response Builder object.
     */
    public static function init(string $requestId, string $status): self
    {
        return new self(new M429ErrorResponse($requestId, $status));
    }

    /**
     * Sets errors field.
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new m429 error response object.
     */
    public function build(): M429ErrorResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
