<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\OpeningHoursObject;

/**
 * Builder for model OpeningHoursObject
 *
 * @see OpeningHoursObject
 */
class OpeningHoursObjectBuilder
{
    /**
     * @var OpeningHoursObject
     */
    private $instance;

    private function __construct(OpeningHoursObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new opening hours object Builder object.
     */
    public static function init(): self
    {
        return new self(new OpeningHoursObject());
    }

    /**
     * Sets week day field.
     */
    public function weekDay(?string $value): self
    {
        $this->instance->setWeekDay($value);
        return $this;
    }

    /**
     * Sets start time field.
     */
    public function startTime(?string $value): self
    {
        $this->instance->setStartTime($value);
        return $this;
    }

    /**
     * Sets end time field.
     */
    public function endTime(?string $value): self
    {
        $this->instance->setEndTime($value);
        return $this;
    }

    /**
     * Initializes a new opening hours object object.
     */
    public function build(): OpeningHoursObject
    {
        return CoreHelper::clone($this->instance);
    }
}
