<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\RatelimitErrMsg;

/**
 * Builder for model RatelimitErrMsg
 *
 * @see RatelimitErrMsg
 */
class RatelimitErrMsgBuilder
{
    /**
     * @var RatelimitErrMsg
     */
    private $instance;

    private function __construct(RatelimitErrMsg $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Ratelimit Err Msg Builder object.
     */
    public static function init(): self
    {
        return new self(new RatelimitErrMsg());
    }

    /**
     * Sets code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets details field.
     *
     * @param string[]|null $value
     */
    public function details(?array $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Initializes a new Ratelimit Err Msg object.
     */
    public function build(): RatelimitErrMsg
    {
        return CoreHelper::clone($this->instance);
    }
}
