<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\ResponseError401AllOf1;

/**
 * Builder for model ResponseError401AllOf1
 *
 * @see ResponseError401AllOf1
 */
class ResponseError401AllOf1Builder
{
    /**
     * @var ResponseError401AllOf1
     */
    private $instance;

    private function __construct(ResponseError401AllOf1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new response error 401 all of 1 Builder object.
     */
    public static function init(array $errors): self
    {
        return new self(new ResponseError401AllOf1($errors));
    }

    /**
     * Initializes a new response error 401 all of 1 object.
     */
    public function build(): ResponseError401AllOf1
    {
        return CoreHelper::clone($this->instance);
    }
}
