<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\StopChargeSessionRequestBodyJson;

/**
 * Builder for model StopChargeSessionRequestBodyJson
 *
 * @see StopChargeSessionRequestBodyJson
 */
class StopChargeSessionRequestBodyJsonBuilder
{
    /**
     * @var StopChargeSessionRequestBodyJson
     */
    private $instance;

    private function __construct(StopChargeSessionRequestBodyJson $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new stop charge session request body json Builder object.
     */
    public static function init(string $sesssionId): self
    {
        return new self(new StopChargeSessionRequestBodyJson($sesssionId));
    }

    /**
     * Initializes a new stop charge session request body json object.
     */
    public function build(): StopChargeSessionRequestBodyJson
    {
        return CoreHelper::clone($this->instance);
    }
}
