<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\TariffVO;

/**
 * Builder for model TariffVO
 *
 * @see TariffVO
 */
class TariffVOBuilder
{
    /**
     * @var TariffVO
     */
    private $instance;

    private function __construct(TariffVO $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new tariff vo Builder object.
     */
    public static function init(): self
    {
        return new self(new TariffVO());
    }

    /**
     * Sets start fee field.
     */
    public function startFee(?float $value): self
    {
        $this->instance->setStartFee($value);
        return $this;
    }

    /**
     * Sets per minute field.
     */
    public function perMinute(?float $value): self
    {
        $this->instance->setPerMinute($value);
        return $this;
    }

    /**
     * Sets per kwh field.
     */
    public function perKWh(?float $value): self
    {
        $this->instance->setPerKWh($value);
        return $this;
    }

    /**
     * Sets currency field.
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets updated field.
     */
    public function updated(?string $value): self
    {
        $this->instance->setUpdated($value);
        return $this;
    }

    /**
     * Sets updated by field.
     */
    public function updatedBy(?string $value): self
    {
        $this->instance->setUpdatedBy($value);
        return $this;
    }

    /**
     * Sets structure field.
     */
    public function structure(?string $value): self
    {
        $this->instance->setStructure($value);
        return $this;
    }

    /**
     * Initializes a new tariff vo object.
     */
    public function build(): TariffVO
    {
        return CoreHelper::clone($this->instance);
    }
}
