<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellEVLib\Models\UnauthorizedErrMsg;

/**
 * Builder for model UnauthorizedErrMsg
 *
 * @see UnauthorizedErrMsg
 */
class UnauthorizedErrMsgBuilder
{
    /**
     * @var UnauthorizedErrMsg
     */
    private $instance;

    private function __construct(UnauthorizedErrMsg $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new unauthorized err msg Builder object.
     */
    public static function init(): self
    {
        return new self(new UnauthorizedErrMsg());
    }

    /**
     * Sets code field.
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets details field.
     */
    public function details(?array $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Initializes a new unauthorized err msg object.
     */
    public function build(): UnauthorizedErrMsg
    {
        return CoreHelper::clone($this->instance);
    }
}
