<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Exceptions;

class HTTP401ErrorResponseException extends ApiException
{
    /**
     * @var string
     */
    private $requestId;

    /**
     * @var string
     */
    private $status;

    /**
     * @var \ShellEVLib\Models\ResponseError401AllOf1ErrorsItems[]
     */
    private $errors;

    /**
     * @param string $reason
     * @param \ShellEVLib\Http\HttpRequest $request
     * @param \ShellEVLib\Http\HttpResponse $response
     * @param string $requestId
     * @param string $status
     * @param \ShellEVLib\Models\ResponseError401AllOf1ErrorsItems[] $errors
     */
    public function __construct(
        string $reason,
        \ShellEVLib\Http\HttpRequest $request,
        \ShellEVLib\Http\HttpResponse $response,
        string $requestId,
        string $status,
        array $errors
    ) {
        parent::__construct($reason, $request, $response);
        $this->requestId = $requestId;
        $this->status = $status;
        $this->errors = $errors;
    }

    /**
     * Returns Request Id.
     * A unique request id in GUID format. The value is written to the Shell API Platform audit log for end
     * to end traceability of a request.
     */
    public function getRequestId(): string
    {
        return $this->requestId;
    }

    /**
     * Sets Request Id.
     * A unique request id in GUID format. The value is written to the Shell API Platform audit log for end
     * to end traceability of a request.
     *
     * @required
     * @maps RequestId
     */
    public function setRequestId(string $requestId): void
    {
        $this->requestId = $requestId;
    }

    /**
     * Returns Status.
     * Indicates overall status of the request
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Indicates overall status of the request
     *
     * @required
     * @maps Status
     * @factory \ShellEVLib\Models\ResponseBaseStatusEnum::checkValue
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Errors.
     * Details of error(s) encountered
     *
     * @return \ShellEVLib\Models\ResponseError401AllOf1ErrorsItems[]
     */
    public function getErrors(): array
    {
        return $this->errors;
    }

    /**
     * Sets Errors.
     * Details of error(s) encountered
     *
     * @required
     * @maps Errors
     *
     * @param \ShellEVLib\Models\ResponseError401AllOf1ErrorsItems[] $errors
     */
    public function setErrors(array $errors): void
    {
        $this->errors = $errors;
    }
}
