<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use stdClass;

/**
 * Accessibility of the Location
 */
class Accessibility implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $remark;

    /**
     * Returns Status.
     * Accessibility Status
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Accessibility Status
     *
     * @maps status
     * @factory \ShellEVLib\Models\AccessibilityStatusEnum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Remark.
     * optional Arbitrary text about restrictions of the Location
     */
    public function getRemark(): ?string
    {
        return $this->remark;
    }

    /**
     * Sets Remark.
     * optional Arbitrary text about restrictions of the Location
     *
     * @maps remark
     */
    public function setRemark(?string $remark): void
    {
        $this->remark = $remark;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->status)) {
            $json['status'] = AccessibilityStatusEnum::checkValue($this->status);
        }
        if (isset($this->remark)) {
            $json['remark'] = $this->remark;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
