<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use stdClass;

/**
 * Address of the Shell Recharge Location
 */
class Address implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $streetAndNumber;

    /**
     * @var string|null
     */
    private $postalCode;

    /**
     * @var string|null
     */
    private $city;

    /**
     * @var string|null
     */
    private $country;

    /**
     * Returns Street and Number.
     * Street Name and Number of the Shell Recharge Location
     */
    public function getStreetAndNumber(): ?string
    {
        return $this->streetAndNumber;
    }

    /**
     * Sets Street and Number.
     * Street Name and Number of the Shell Recharge Location
     *
     * @maps streetAndNumber
     */
    public function setStreetAndNumber(?string $streetAndNumber): void
    {
        $this->streetAndNumber = $streetAndNumber;
    }

    /**
     * Returns Postal Code.
     * Postal Code of the Shell Recharge Location
     */
    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    /**
     * Sets Postal Code.
     * Postal Code of the Shell Recharge Location
     *
     * @maps postalCode
     */
    public function setPostalCode(?string $postalCode): void
    {
        $this->postalCode = $postalCode;
    }

    /**
     * Returns City.
     * City name of the Shell Recharge Location
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * Sets City.
     * City name of the Shell Recharge Location
     *
     * @maps city
     */
    public function setCity(?string $city): void
    {
        $this->city = $city;
    }

    /**
     * Returns Country.
     * ISO 3166 Alpha-2 Country Code of the Shell Recharge Location
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * Sets Country.
     * ISO 3166 Alpha-2 Country Code of the Shell Recharge Location
     *
     * @maps country
     */
    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->streetAndNumber)) {
            $json['streetAndNumber'] = $this->streetAndNumber;
        }
        if (isset($this->postalCode)) {
            $json['postalCode']      = $this->postalCode;
        }
        if (isset($this->city)) {
            $json['city']            = $this->city;
        }
        if (isset($this->country)) {
            $json['country']         = $this->country;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
