<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use stdClass;

class ChargesessionStartBody implements \JsonSerializable
{
    /**
     * @var string
     */
    private $evChargeNumber;

    /**
     * @var string
     */
    private $evseId;

    /**
     * @param string $evChargeNumber
     * @param string $evseId
     */
    public function __construct(string $evChargeNumber, string $evseId)
    {
        $this->evChargeNumber = $evChargeNumber;
        $this->evseId = $evseId;
    }

    /**
     * Returns Ev Charge Number.
     * The EV Charge Number which can be found on the back of the Shell EV Card
     */
    public function getEvChargeNumber(): string
    {
        return $this->evChargeNumber;
    }

    /**
     * Sets Ev Charge Number.
     * The EV Charge Number which can be found on the back of the Shell EV Card
     *
     * @required
     * @maps EvChargeNumber
     */
    public function setEvChargeNumber(string $evChargeNumber): void
    {
        $this->evChargeNumber = $evChargeNumber;
    }

    /**
     * Returns Evse Id.
     * Standard EVSE (Electric Vehicle Supply Equipment) Id identifier (ISO-IEC-15118)
     */
    public function getEvseId(): string
    {
        return $this->evseId;
    }

    /**
     * Sets Evse Id.
     * Standard EVSE (Electric Vehicle Supply Equipment) Id identifier (ISO-IEC-15118)
     *
     * @required
     * @maps EvseId
     */
    public function setEvseId(string $evseId): void
    {
        $this->evseId = $evseId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['EvChargeNumber'] = $this->evChargeNumber;
        $json['EvseId']         = $this->evseId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
