<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use ShellEVLib\ApiHelper;
use ShellEVLib\Utils\DateTimeHelper;
use stdClass;

class DataActive implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $userId;

    /**
     * @var string|null
     */
    private $emaId;

    /**
     * @var string|null
     */
    private $evseId;

    /**
     * @var \DateTime|null
     */
    private $startedAt;

    /**
     * @var array
     */
    private $stoppedAt = [];

    /**
     * @var ChargeRetrieveState|null
     */
    private $sessionState;

    /**
     * @var string|null
     */
    private $lastUpdated;

    /**
     * Returns Id.
     * Id of the session
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Id of the session
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns User Id.
     * Id of the user that started the session
     */
    public function getUserId(): ?string
    {
        return $this->userId;
    }

    /**
     * Sets User Id.
     * Id of the user that started the session
     *
     * @maps userId
     */
    public function setUserId(?string $userId): void
    {
        $this->userId = $userId;
    }

    /**
     * Returns Ema Id.
     * Id of the evse that the user is charging
     */
    public function getEmaId(): ?string
    {
        return $this->emaId;
    }

    /**
     * Sets Ema Id.
     * Id of the evse that the user is charging
     *
     * @maps emaId
     */
    public function setEmaId(?string $emaId): void
    {
        $this->emaId = $emaId;
    }

    /**
     * Returns Evse Id.
     * Electric Vehicle Supply Equipment Identifier. An EVSEID identifies a Charging Point.
     */
    public function getEvseId(): ?string
    {
        return $this->evseId;
    }

    /**
     * Sets Evse Id.
     * Electric Vehicle Supply Equipment Identifier. An EVSEID identifies a Charging Point.
     *
     * @maps evseId
     */
    public function setEvseId(?string $evseId): void
    {
        $this->evseId = $evseId;
    }

    /**
     * Returns Started At.
     * When the session is started
     */
    public function getStartedAt(): ?\DateTime
    {
        return $this->startedAt;
    }

    /**
     * Sets Started At.
     * When the session is started
     *
     * @maps startedAt
     * @factory \ShellEVLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setStartedAt(?\DateTime $startedAt): void
    {
        $this->startedAt = $startedAt;
    }

    /**
     * Returns Stopped At.
     * When the session is stopped
     */
    public function getStoppedAt(): ?\DateTime
    {
        if (count($this->stoppedAt) == 0) {
            return null;
        }
        return $this->stoppedAt['value'];
    }

    /**
     * Sets Stopped At.
     * When the session is stopped
     *
     * @maps stoppedAt
     * @factory \ShellEVLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setStoppedAt(?\DateTime $stoppedAt): void
    {
        $this->stoppedAt['value'] = $stoppedAt;
    }

    /**
     * Unsets Stopped At.
     * When the session is stopped
     */
    public function unsetStoppedAt(): void
    {
        $this->stoppedAt = [];
    }

    /**
     * Returns Session State.
     */
    public function getSessionState(): ?ChargeRetrieveState
    {
        return $this->sessionState;
    }

    /**
     * Sets Session State.
     *
     * @maps SessionState
     */
    public function setSessionState(?ChargeRetrieveState $sessionState): void
    {
        $this->sessionState = $sessionState;
    }

    /**
     * Returns Last Updated.
     */
    public function getLastUpdated(): ?string
    {
        return $this->lastUpdated;
    }

    /**
     * Sets Last Updated.
     *
     * @maps lastUpdated
     */
    public function setLastUpdated(?string $lastUpdated): void
    {
        $this->lastUpdated = $lastUpdated;
    }

    /**
     * Converts the DataActive object to a human-readable string representation.
     *
     * @return string The string representation of the DataActive object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'DataActive',
            [
                'id' => $this->id,
                'userId' => $this->userId,
                'emaId' => $this->emaId,
                'evseId' => $this->evseId,
                'startedAt' => $this->startedAt,
                'stoppedAt' => $this->getStoppedAt(),
                'sessionState' => $this->sessionState,
                'lastUpdated' => $this->lastUpdated
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']           = $this->id;
        }
        if (isset($this->userId)) {
            $json['userId']       = $this->userId;
        }
        if (isset($this->emaId)) {
            $json['emaId']        = $this->emaId;
        }
        if (isset($this->evseId)) {
            $json['evseId']       = $this->evseId;
        }
        if (isset($this->startedAt)) {
            $json['startedAt']    = DateTimeHelper::toRfc3339DateTime($this->startedAt);
        }
        if (!empty($this->stoppedAt)) {
            $json['stoppedAt']    = DateTimeHelper::toRfc3339DateTime($this->stoppedAt['value']);
        }
        if (isset($this->sessionState)) {
            $json['SessionState'] = $this->sessionState;
        }
        if (isset($this->lastUpdated)) {
            $json['lastUpdated']  = $this->lastUpdated;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
