<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use ShellEVLib\ApiHelper;
use stdClass;

class InlineResponse202Data implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $sessionId;

    /**
     * Returns Session Id.
     * Session Id for tracking.
     */
    public function getSessionId(): ?string
    {
        return $this->sessionId;
    }

    /**
     * Sets Session Id.
     * Session Id for tracking.
     *
     * @maps sessionId
     */
    public function setSessionId(?string $sessionId): void
    {
        $this->sessionId = $sessionId;
    }

    /**
     * Converts the InlineResponse202Data object to a human-readable string representation.
     *
     * @return string The string representation of the InlineResponse202Data object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('InlineResponse202Data', ['sessionId' => $this->sessionId]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->sessionId)) {
            $json['sessionId'] = $this->sessionId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
