<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use stdClass;

class OpeningHoursObject implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $weekDay;

    /**
     * @var string|null
     */
    private $startTime;

    /**
     * @var string|null
     */
    private $endTime;

    /**
     * Returns Week Day.
     * 3 letter day of the week
     */
    public function getWeekDay(): ?string
    {
        return $this->weekDay;
    }

    /**
     * Sets Week Day.
     * 3 letter day of the week
     *
     * @maps weekDay
     * @factory \ShellEVLib\Models\OpeningHoursObjectWeekDayEnum::checkValue
     */
    public function setWeekDay(?string $weekDay): void
    {
        $this->weekDay = $weekDay;
    }

    /**
     * Returns Start Time.
     * Hour in 24h local time when the location opens.
     */
    public function getStartTime(): ?string
    {
        return $this->startTime;
    }

    /**
     * Sets Start Time.
     * Hour in 24h local time when the location opens.
     *
     * @maps startTime
     */
    public function setStartTime(?string $startTime): void
    {
        $this->startTime = $startTime;
    }

    /**
     * Returns End Time.
     * Hour in 24h local time when the location closes.
     */
    public function getEndTime(): ?string
    {
        return $this->endTime;
    }

    /**
     * Sets End Time.
     * Hour in 24h local time when the location closes.
     *
     * @maps endTime
     */
    public function setEndTime(?string $endTime): void
    {
        $this->endTime = $endTime;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->weekDay)) {
            $json['weekDay']   = OpeningHoursObjectWeekDayEnum::checkValue($this->weekDay);
        }
        if (isset($this->startTime)) {
            $json['startTime'] = $this->startTime;
        }
        if (isset($this->endTime)) {
            $json['endTime']   = $this->endTime;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
