<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * 3 letter day of the week
 */
class OpeningHoursObjectWeekDayEnum
{
    public const SUN = 'Sun';

    public const MON = 'Mon';

    public const TUE = 'Tue';

    public const WED = 'Wed';

    public const THU = 'Thu';

    public const FRI = 'Fri';

    public const SAT = 'Sat';

    private const _ALL_VALUES = [self::SUN, self::MON, self::TUE, self::WED, self::THU, self::FRI, self::SAT];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for OpeningHoursObjectWeekDayEnum.");
    }
}
