<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use ShellEVLib\ApiHelper;
use stdClass;

class Response implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $requestId;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var LocationResponeObject[]|null
     */
    private $data;

    /**
     * Returns Request Id.
     * requestId is unique identifier value that is attached to requests and messages that allow reference
     * to a particular transaction or event chain.
     */
    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * Sets Request Id.
     * requestId is unique identifier value that is attached to requests and messages that allow reference
     * to a particular transaction or event chain.
     *
     * @maps requestId
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId = $requestId;
    }

    /**
     * Returns Status.
     * status of the API call
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * status of the API call
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Data.
     * API Response
     *
     * @return LocationResponeObject[]|null
     */
    public function getData(): ?array
    {
        return $this->data;
    }

    /**
     * Sets Data.
     * API Response
     *
     * @maps data
     *
     * @param LocationResponeObject[]|null $data
     */
    public function setData(?array $data): void
    {
        $this->data = $data;
    }

    /**
     * Converts the Response object to a human-readable string representation.
     *
     * @return string The string representation of the Response object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Response',
            ['requestId' => $this->requestId, 'status' => $this->status, 'data' => $this->data]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->requestId)) {
            $json['requestId'] = $this->requestId;
        }
        if (isset($this->status)) {
            $json['status']    = $this->status;
        }
        if (isset($this->data)) {
            $json['data']      = $this->data;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
