<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib\Models;

use stdClass;

class StopChargeSessionRequestBodyJson implements \JsonSerializable
{
    /**
     * @var string
     */
    private $sesssionId;

    /**
     * @param string $sesssionId
     */
    public function __construct(string $sesssionId)
    {
        $this->sesssionId = $sesssionId;
    }

    /**
     * Returns Sesssion Id.
     * Session Id is to be fetched
     */
    public function getSesssionId(): string
    {
        return $this->sesssionId;
    }

    /**
     * Sets Sesssion Id.
     * Session Id is to be fetched
     *
     * @required
     * @maps SesssionId
     */
    public function setSesssionId(string $sesssionId): void
    {
        $this->sesssionId = $sesssionId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['SesssionId'] = $this->sesssionId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
