<?php

declare(strict_types=1);

/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellEVLib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * Production Server
     */
    public const PRODUCTION = 'production';

    /**
     * Test Server
     */
    public const ENVIRONMENT2 = 'environment2';
}
